### ISSUE TITLE
How to visualise prediction?

### ISSUE THREAD

**Issue by jamesbayne** [FTD007/PInet#6]
Hi,

Sorry for opening another issue. I was wondering how I can visualise the predicted binding interfaces as is done in the paper? I've got to the point where I can run `SimplePredictor.py` which outputs `2I25_prob_r_l.seg` file and `PredictionPoint2Residue.py` which outputs `2I25_resi_r.seg` and `2I25_resi_l.seg`. I was wondering if there's a script for visualising the results in PyMOL?

Thank you!

**Comment by jamesbayne** [comment]
<img width="500" alt="Screenshot 2021-08-06 at 22 49 43" src="https://user-images.githubusercontent.com/37155931/128574583-26cfb9f3-482e-476b-81c2-6c3d5d6dc5d0.png">

Also I think there may be an issue with rotational invariance. The first image is the prediction (using colour by b-factor) for the threefold axis for AAV2 (PDB_ID=6NZ0) with a PKD domain from AAVR (which should be symmetrical about about the threefold axis) yet clearly the prediction is asymmetrical. 

The second image has the AAVR domain superimposed.
<img width="425" alt="Screenshot 2021-08-06 at 23 02 02" src="https://user-images.githubusercontent.com/37155931/128575237-6e8dec1e-d182-4f21-96df-fe550a955ac8.png">
 It seems that the program makes a very different prediction for the viral capsid monomer (there are 3 monomers for the full 3-fold axis shown (hence the rotational symmetry)) that binds the particular AAVR domain given even though the binding has symmetry (as shown in the [PDB structure](https://www.rcsb.org/structure/6NZ0))

**Comment by FTD007** [comment]
Hi James, your comments are super valuable! The current visualization script is little complicated but I will try to make it available asap! 

For the AAV2 prediction the result is interesting. The model is train for pairs of protein from complexes, which mostly only have 1 stable binding sites. This means the predicition will have constraints in term of prediction size of binding site. I would say it would be super intersting to see prediction of 1 monomer against AAVR since the binding site seems only on one monomer. Let me know if there are more I can help!!! It is an interesting question!

**Comment by jamesbayne** [comment]
Thanks for getting back to me, this project on AAV2 is part of my PhD work and I'd like to explore PInet further. Would it be possible for me to follow up via email? Not sure that a repo issue is the best format going forward!

**Comment by FTD007** [comment]
sure thing! you can reach me at Bowen.Dai.GR@dartmouth.edu
